# dependabot.yml file with
# customized nuget configuration

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Cirrious.FluentLayout.Extensions"
    target-branch: "develop"
    schedule:
      interval: "daily"
